### ISSUE TITLE
Создание базовых таблиц в базе данных

### ISSUE THREAD

**Issue by fomgleb** [fomgleb/uchat#6]
Сделать функции которые создают таблицы: Messages, Chats и как-то правильно их связать.

**Comment by fomgleb** [comment]
От вроде норм таблицы: https://unetway.com/blog/proektirovanie-arhitektury-bazy-dannyh-dla-cata

**Comment by serdekh** [comment]
![database system](https://user-images.githubusercontent.com/116834958/214391974-f17dca2c-6c3f-4f52-a32c-fee3b2185b4a.png)
